name: traders
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5 
  # DateTime
  jiffy: ^6.2.1 
  intl: ^0.18.0 
  http: ^1.1.0 
  # Images
  cached_network_image: ^3.2.3 
  image_picker: ^1.0.4 
 
  # Animate
  show_up_animation: ^2.0.0 
  auto_animated: ^3.2.0 
  # Google Map
  flutter_polyline_points: ^2.0.0 
  google_maps_flutter: ^2.5.0 
  geolocator: ^10.0.1 
  geocoding: ^2.1.0 
  # Firebase And Notification 
  #firebase_messaging: ^14.6.7 
  #firebase_core: ^2.15.1 
  #flutter_local_notifications: ^15.1.1 
  #cloud_firestore: ^4.9.1 
  # Local Data Cache
  sqflite: ^2.3.0 
  shared_preferences: ^2.2.1
  

  # Qrcode 
  qr_flutter: ^4.1.0 
  scan: ^1.6.0 
  grouped_list: ^5.1.2 
  url_launcher: ^6.1.14 
  dropdown_search: ^5.0.6 
  badges: ^3.1.2 
  # Icon 
  # flutter_svg: 
  font_awesome_flutter: ^10.5.0 
  fluttericon: ^2.0.0 
  dartz: ^0.10.1 
  # Google Auth
  google_sign_in: ^6.1.5 
 
  device_preview: ^1.1.0 
  responsive_builder: ^0.7.0 
  image_pickers: ^2.0.4+2 
  path: ^1.8.3
  provider: ^6.0.5
  flutter_otp_text_field: ^1.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: fonts
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 500
          style: italic
       
    - family: TrajanPro
      fonts:
        - asset: assets/fontsRale/RobotoCondensed-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
